export default {
  '0e384e19': [() => import(/* webpackChunkName: '0e384e19' */ '@site/docs/intro.md'), '@site/docs/intro.md', require.resolveWeak('@site/docs/intro.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '7f955e7e': [() => import(/* webpackChunkName: '7f955e7e' */ '@site/docs/modules/ros2-humanoid/intro.md'), '@site/docs/modules/ros2-humanoid/intro.md', require.resolveWeak('@site/docs/modules/ros2-humanoid/intro.md')],
  '88b28ec5': [() => import(/* webpackChunkName: '88b28ec5' */ '@site/docs/modules/physical-ai/intro.md'), '@site/docs/modules/physical-ai/intro.md', require.resolveWeak('@site/docs/modules/physical-ai/intro.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'bba3b20f': [() => import(/* webpackChunkName: 'bba3b20f' */ 'E:\\Hammad97 Docs\\Quater 4\\hackathon-1\\hackathon-1-ai-book\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json'), 'E:\\Hammad97 Docs\\Quater 4\\hackathon-1\\hackathon-1-ai-book\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json', require.resolveWeak('E:\\Hammad97 Docs\\Quater 4\\hackathon-1\\hackathon-1-ai-book\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],
  'f432c2e5': [() => import(/* webpackChunkName: 'f432c2e5' */ 'E:\\Hammad97 Docs\\Quater 4\\hackathon-1\\hackathon-1-ai-book\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json'), 'E:\\Hammad97 Docs\\Quater 4\\hackathon-1\\hackathon-1-ai-book\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json', require.resolveWeak('E:\\Hammad97 Docs\\Quater 4\\hackathon-1\\hackathon-1-ai-book\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json')],};
